LARAVEL/routes/web.php
<?php
Route::get('/welcome', function(){
    return view('welcome');
});
Route::get('/offline', function(){
    return view('modules/laravelpwa/offline');
});
Route::redirect('/', '/login');

Route::get('/home', function () {
    if (session('status')) {
        return redirect()->route('admin.home')->with('status', session('status'));
    }

    return redirect()->route('admin.home');
});

Auth::routes();
// Admin

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    // Permissions
    Route::delete('permissions/destroy', 'PermissionsController@massDestroy')->name('permissions.massDestroy');
    Route::resource('permissions', 'PermissionsController');

    // Roles
    Route::delete('roles/destroy', 'RolesController@massDestroy')->name('roles.massDestroy');
    Route::resource('roles', 'RolesController');

    // Users
    Route::delete('users/destroy', 'UsersController@massDestroy')->name('users.massDestroy');
    Route::post('users/parse-csv-import', 'UsersController@parseCsvImport')->name('users.parseCsvImport');
    Route::post('users/process-csv-import', 'UsersController@processCsvImport')->name('users.processCsvImport');
    Route::resource('users', 'UsersController');

    // Categoria
    Route::delete('categoria/destroy', 'CategoriaController@massDestroy')->name('categoria.massDestroy');
    Route::post('categoria/media', 'CategoriaController@storeMedia')->name('categoria.storeMedia');
    Route::post('categoria/ckmedia', 'CategoriaController@storeCKEditorImages')->name('categoria.storeCKEditorImages');
    Route::post('categoria/parse-csv-import', 'CategoriaController@parseCsvImport')->name('categoria.parseCsvImport');
    Route::post('categoria/process-csv-import', 'CategoriaController@processCsvImport')->name('categoria.processCsvImport');
    Route::resource('categoria', 'CategoriaController');

    // Clasificacions
    Route::delete('clasificacions/destroy', 'ClasificacionController@massDestroy')->name('clasificacions.massDestroy');
    Route::post('clasificacions/media', 'ClasificacionController@storeMedia')->name('clasificacions.storeMedia');
    Route::post('clasificacions/ckmedia', 'ClasificacionController@storeCKEditorImages')->name('clasificacions.storeCKEditorImages');
    Route::post('clasificacions/parse-csv-import', 'ClasificacionController@parseCsvImport')->name('clasificacions.parseCsvImport');
    Route::post('clasificacions/process-csv-import', 'ClasificacionController@processCsvImport')->name('clasificacions.processCsvImport');
    Route::resource('clasificacions', 'ClasificacionController');

    // Autors
    Route::delete('autors/destroy', 'AutorController@massDestroy')->name('autors.massDestroy');
    Route::post('autors/parse-csv-import', 'AutorController@parseCsvImport')->name('autors.parseCsvImport');
    Route::post('autors/process-csv-import', 'AutorController@processCsvImport')->name('autors.processCsvImport');
    Route::resource('autors', 'AutorController');

    // Peliculas
    Route::delete('peliculas/destroy', 'PeliculasController@massDestroy')->name('peliculas.massDestroy');
    Route::post('peliculas/parse-csv-import', 'PeliculasController@parseCsvImport')->name('peliculas.parseCsvImport');
    Route::post('peliculas/process-csv-import', 'PeliculasController@processCsvImport')->name('peliculas.processCsvImport');
    Route::resource('peliculas', 'PeliculasController');

    // Boletos
    Route::delete('boletos/destroy', 'BoletosController@massDestroy')->name('boletos.massDestroy');
    Route::post('boletos/parse-csv-import', 'BoletosController@parseCsvImport')->name('boletos.parseCsvImport');
    Route::post('boletos/process-csv-import', 'BoletosController@processCsvImport')->name('boletos.processCsvImport');
    Route::resource('boletos', 'BoletosController');

    // Ctg Clientes
    Route::delete('ctg-clientes/destroy', 'CtgClienteController@massDestroy')->name('ctg-clientes.massDestroy');
    Route::post('ctg-clientes/media', 'CtgClienteController@storeMedia')->name('ctg-clientes.storeMedia');
    Route::post('ctg-clientes/ckmedia', 'CtgClienteController@storeCKEditorImages')->name('ctg-clientes.storeCKEditorImages');
    Route::post('ctg-clientes/parse-csv-import', 'CtgClienteController@parseCsvImport')->name('ctg-clientes.parseCsvImport');
    Route::post('ctg-clientes/process-csv-import', 'CtgClienteController@processCsvImport')->name('ctg-clientes.processCsvImport');
    Route::resource('ctg-clientes', 'CtgClienteController');

    // Clientecategoria
    Route::delete('clientecategoria/destroy', 'ClientecategoriaController@massDestroy')->name('clientecategoria.massDestroy');
    Route::post('clientecategoria/parse-csv-import', 'ClientecategoriaController@parseCsvImport')->name('clientecategoria.parseCsvImport');
    Route::post('clientecategoria/process-csv-import', 'ClientecategoriaController@processCsvImport')->name('clientecategoria.processCsvImport');
    Route::resource('clientecategoria', 'ClientecategoriaController');

    // Asientos
    Route::delete('asientos/destroy', 'AsientosController@massDestroy')->name('asientos.massDestroy');
    Route::post('asientos/parse-csv-import', 'AsientosController@parseCsvImport')->name('asientos.parseCsvImport');
    Route::post('asientos/process-csv-import', 'AsientosController@processCsvImport')->name('asientos.processCsvImport');
    Route::resource('asientos', 'AsientosController');

    // Salas
    Route::delete('salas/destroy', 'SalasController@massDestroy')->name('salas.massDestroy');
    Route::post('salas/parse-csv-import', 'SalasController@parseCsvImport')->name('salas.parseCsvImport');
    Route::post('salas/process-csv-import', 'SalasController@processCsvImport')->name('salas.processCsvImport');
    Route::resource('salas', 'SalasController');

    // Tickets
    Route::delete('tickets/destroy', 'TicketController@massDestroy')->name('tickets.massDestroy');
    Route::post('tickets/parse-csv-import', 'TicketController@parseCsvImport')->name('tickets.parseCsvImport');
    Route::post('tickets/process-csv-import', 'TicketController@processCsvImport')->name('tickets.processCsvImport');
    Route::resource('tickets', 'TicketController');

    // Teams
    Route::delete('teams/destroy', 'TeamController@massDestroy')->name('teams.massDestroy');
    Route::resource('teams', 'TeamController');

    Route::get('system-calendar', 'SystemCalendarController@index')->name('systemCalendar');
    Route::get('messenger', 'MessengerController@index')->name('messenger.index');
    Route::get('messenger/create', 'MessengerController@createTopic')->name('messenger.createTopic');
    Route::post('messenger', 'MessengerController@storeTopic')->name('messenger.storeTopic');
    Route::get('messenger/inbox', 'MessengerController@showInbox')->name('messenger.showInbox');
    Route::get('messenger/outbox', 'MessengerController@showOutbox')->name('messenger.showOutbox');
    Route::get('messenger/{topic}', 'MessengerController@showMessages')->name('messenger.showMessages');
    Route::delete('messenger/{topic}', 'MessengerController@destroyTopic')->name('messenger.destroyTopic');
    Route::post('messenger/{topic}/reply', 'MessengerController@replyToTopic')->name('messenger.reply');
    Route::get('messenger/{topic}/reply', 'MessengerController@showReply')->name('messenger.showReply');
});

LARAVEL/app/Team.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Team extends Model
{
    use SoftDeletes;

    public $table = 'teams';

    protected $dates = [
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    protected $fillable = [
        'name',
        'created_at',
        'updated_at',
        'deleted_at',
    ];
}

LARAVEL/app/Http/Controllers/Admin/TeamController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\MassDestroyTeamRequest;
use App\Http\Requests\StoreTeamRequest;
use App\Http\Requests\UpdateTeamRequest;
use App\Team;
use Gate;
use Illuminate\Http\Request;
use Symfony\Component\HttpFoundation\Response;

class TeamController extends Controller
{
    public function index()
    {
        abort_if(Gate::denies('team_access'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $teams = Team::all();

        return view('admin.teams.index', compact('teams'));
    }

    public function create()
    {
        abort_if(Gate::denies('team_create'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        return view('admin.teams.create');
    }

    public function store(StoreTeamRequest $request)
    {
        $team = Team::create($request->all());

        return redirect()->route('admin.teams.index');

    }

    public function edit(Team $team)
    {
        abort_if(Gate::denies('team_edit'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        return view('admin.teams.edit', compact('team'));
    }

    public function update(UpdateTeamRequest $request, Team $team)
    {
        $team->update($request->all());

        return redirect()->route('admin.teams.index');

    }

    public function show(Team $team)
    {
        abort_if(Gate::denies('team_show'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        return view('admin.teams.show', compact('team'));
    }

    public function destroy(Team $team)
    {
        abort_if(Gate::denies('team_delete'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $team->delete();

        return back();

    }

    public function massDestroy(MassDestroyTeamRequest $request)
    {
        Team::whereIn('id', request('ids'))->delete();

        return response(null, Response::HTTP_NO_CONTENT);

    }
}

LARAVEL/resources/views/admin/teams/create.blade.php
@extends('layouts.admin')
@section('content')
<div class="content">

    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    {{ trans('global.create') }} {{ trans('cruds.team.title_singular') }}
                </div>
                <div class="panel-body">
                    <form method="POST" action="{{ route("admin.teams.store") }}" enctype="multipart/form-data">
                        @csrf
                        <div class="form-group {{ $errors->has('name') ? 'has-error' : '' }}">
                            <label class="required" for="name">{{ trans('cruds.team.fields.name') }}</label>
                            <input class="form-control" type="text" name="name" id="name" value="{{ old('name', '') }}" required>
                            @if($errors->has('name'))
                                <span class="help-block" role="alert">{{ $errors->first('name') }}</span>
                            @endif
                            <span class="help-block">{{ trans('cruds.team.fields.name_helper') }}</span>
                        </div>
                        <div class="form-group">
                            <button class="btn btn-danger" type="submit">
                                {{ trans('global.save') }}
                            </button>
                        </div>
                    </form>
                </div>
            </div>



        </div>
    </div>
</div>
@endsection

LARAVEL/resources/views/admin/teams/edit.blade.php
@extends('layouts.admin')
@section('content')
<div class="content">

    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    {{ trans('global.edit') }} {{ trans('cruds.team.title_singular') }}
                </div>
                <div class="panel-body">
                    <form method="POST" action="{{ route("admin.teams.update", [$team->id]) }}" enctype="multipart/form-data">
                        @method('PUT')
                        @csrf
                        <div class="form-group {{ $errors->has('name') ? 'has-error' : '' }}">
                            <label class="required" for="name">{{ trans('cruds.team.fields.name') }}</label>
                            <input class="form-control" type="text" name="name" id="name" value="{{ old('name', $team->name) }}" required>
                            @if($errors->has('name'))
                                <span class="help-block" role="alert">{{ $errors->first('name') }}</span>
                            @endif
                            <span class="help-block">{{ trans('cruds.team.fields.name_helper') }}</span>
                        </div>
                        <div class="form-group">
                            <button class="btn btn-danger" type="submit">
                                {{ trans('global.save') }}
                            </button>
                        </div>
                    </form>
                </div>
            </div>



        </div>
    </div>
</div>
@endsection

LARAVEL/resources/views/admin/teams/index.blade.php
@extends('layouts.admin')
@section('content')
<div class="content">
    @can('team_create')
        <div style="margin-bottom: 10px;" class="row">
            <div class="col-lg-12">
                <a class="btn btn-success" href="{{ route("admin.teams.create") }}">
                    {{ trans('global.add') }} {{ trans('cruds.team.title_singular') }}
                </a>
            </div>
        </div>
    @endcan
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    {{ trans('cruds.team.title_singular') }} {{ trans('global.list') }}
                </div>
                <div class="panel-body">
                    <div class="table-responsive">
                        <table class=" table table-bordered table-striped table-hover datatable datatable-Team">
                            <thead>
                                <tr>
                                    <th width="10">

                                    </th>
                                    <th>
                                        {{ trans('cruds.team.fields.id') }}
                                    </th>
                                    <th>
                                        {{ trans('cruds.team.fields.name') }}
                                    </th>
                                    <th>
                                        &nbsp;
                                    </th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($teams as $key => $team)
                                    <tr data-entry-id="{{ $team->id }}">
                                        <td>

                                        </td>
                                        <td>
                                            {{ $team->id ?? '' }}
                                        </td>
                                        <td>
                                            {{ $team->name ?? '' }}
                                        </td>
                                        <td>
                                            @can('team_show')
                                                <a class="btn btn-xs btn-primary" href="{{ route('admin.teams.show', $team->id) }}">
                                                    {{ trans('global.view') }}
                                                </a>
                                            @endcan

                                            @can('team_edit')
                                                <a class="btn btn-xs btn-info" href="{{ route('admin.teams.edit', $team->id) }}">
                                                    {{ trans('global.edit') }}
                                                </a>
                                            @endcan

                                            @can('team_delete')
                                                <form action="{{ route('admin.teams.destroy', $team->id) }}" method="POST" onsubmit="return confirm('{{ trans('global.areYouSure') }}');" style="display: inline-block;">
                                                    <input type="hidden" name="_method" value="DELETE">
                                                    <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                                    <input type="submit" class="btn btn-xs btn-danger" value="{{ trans('global.delete') }}">
                                                </form>
                                            @endcan

                                        </td>

                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>



        </div>
    </div>
</div>
@endsection
@section('scripts')
@parent
<script>
    $(function () {
  let dtButtons = $.extend(true, [], $.fn.dataTable.defaults.buttons)
@can('team_delete')
  let deleteButtonTrans = '{{ trans('global.datatables.delete') }}'
  let deleteButton = {
    text: deleteButtonTrans,
    url: "{{ route('admin.teams.massDestroy') }}",
    className: 'btn-danger',
    action: function (e, dt, node, config) {
      var ids = $.map(dt.rows({ selected: true }).nodes(), function (entry) {
          return $(entry).data('entry-id')
      });

      if (ids.length === 0) {
        alert('{{ trans('global.datatables.zero_selected') }}')

        return
      }

      if (confirm('{{ trans('global.areYouSure') }}')) {
        $.ajax({
          headers: {'x-csrf-token': _token},
          method: 'POST',
          url: config.url,
          data: { ids: ids, _method: 'DELETE' }})
          .done(function () { location.reload() })
      }
    }
  }
  dtButtons.push(deleteButton)
@endcan

  $.extend(true, $.fn.dataTable.defaults, {
    order: [[ 1, 'desc' ]],
    pageLength: 100,
  });
  $('.datatable-Team:not(.ajaxTable)').DataTable({ buttons: dtButtons })
    $('a[data-toggle="tab"]').on('shown.bs.tab', function(e){
        $($.fn.dataTable.tables(true)).DataTable()
            .columns.adjust();
    });
})

</script>
@endsection

LARAVEL/resources/views/admin/teams/show.blade.php
@extends('layouts.admin')
@section('content')
<div class="content">

    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    {{ trans('global.show') }} {{ trans('cruds.team.title') }}
                </div>
                <div class="panel-body">
                    <div class="form-group">
                        <div class="form-group">
                            <a class="btn btn-default" href="{{ route('admin.teams.index') }}">
                                {{ trans('global.back_to_list') }}
                            </a>
                        </div>
                        <table class="table table-bordered table-striped">
                            <tbody>
                                <tr>
                                    <th>
                                        {{ trans('cruds.team.fields.id') }}
                                    </th>
                                    <td>
                                        {{ $team->id }}
                                    </td>
                                </tr>
                                <tr>
                                    <th>
                                        {{ trans('cruds.team.fields.name') }}
                                    </th>
                                    <td>
                                        {{ $team->name }}
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                        <div class="form-group">
                            <a class="btn btn-default" href="{{ route('admin.teams.index') }}">
                                {{ trans('global.back_to_list') }}
                            </a>
                        </div>
                    </div>
                </div>
            </div>



        </div>
    </div>
</div>
@endsection