LARAVEL/routes/web.php
<?php
Route::get('/welcome', function(){
    return view('welcome');
});
Route::get('/offline', function(){
    return view('modules/laravelpwa/offline');
});
Route::redirect('/', '/login');

Route::get('/home', function () {
    if (session('status')) {
        return redirect()->route('admin.home')->with('status', session('status'));
    }

    return redirect()->route('admin.home');
});

Auth::routes();
// Admin

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    // Permissions
    Route::delete('permissions/destroy', 'PermissionsController@massDestroy')->name('permissions.massDestroy');
    Route::resource('permissions', 'PermissionsController');

    // Roles
    Route::delete('roles/destroy', 'RolesController@massDestroy')->name('roles.massDestroy');
    Route::resource('roles', 'RolesController');

    // Users
    Route::delete('users/destroy', 'UsersController@massDestroy')->name('users.massDestroy');
    Route::post('users/parse-csv-import', 'UsersController@parseCsvImport')->name('users.parseCsvImport');
    Route::post('users/process-csv-import', 'UsersController@processCsvImport')->name('users.processCsvImport');
    Route::resource('users', 'UsersController');

    // Categoria
    Route::delete('categoria/destroy', 'CategoriaController@massDestroy')->name('categoria.massDestroy');
    Route::post('categoria/media', 'CategoriaController@storeMedia')->name('categoria.storeMedia');
    Route::post('categoria/ckmedia', 'CategoriaController@storeCKEditorImages')->name('categoria.storeCKEditorImages');
    Route::post('categoria/parse-csv-import', 'CategoriaController@parseCsvImport')->name('categoria.parseCsvImport');
    Route::post('categoria/process-csv-import', 'CategoriaController@processCsvImport')->name('categoria.processCsvImport');
    Route::resource('categoria', 'CategoriaController');

    // Clasificacions
    Route::delete('clasificacions/destroy', 'ClasificacionController@massDestroy')->name('clasificacions.massDestroy');
    Route::post('clasificacions/media', 'ClasificacionController@storeMedia')->name('clasificacions.storeMedia');
    Route::post('clasificacions/ckmedia', 'ClasificacionController@storeCKEditorImages')->name('clasificacions.storeCKEditorImages');
    Route::post('clasificacions/parse-csv-import', 'ClasificacionController@parseCsvImport')->name('clasificacions.parseCsvImport');
    Route::post('clasificacions/process-csv-import', 'ClasificacionController@processCsvImport')->name('clasificacions.processCsvImport');
    Route::resource('clasificacions', 'ClasificacionController');

    // Autors
    Route::delete('autors/destroy', 'AutorController@massDestroy')->name('autors.massDestroy');
    Route::post('autors/parse-csv-import', 'AutorController@parseCsvImport')->name('autors.parseCsvImport');
    Route::post('autors/process-csv-import', 'AutorController@processCsvImport')->name('autors.processCsvImport');
    Route::resource('autors', 'AutorController');

    // Peliculas
    Route::delete('peliculas/destroy', 'PeliculasController@massDestroy')->name('peliculas.massDestroy');
    Route::post('peliculas/parse-csv-import', 'PeliculasController@parseCsvImport')->name('peliculas.parseCsvImport');
    Route::post('peliculas/process-csv-import', 'PeliculasController@processCsvImport')->name('peliculas.processCsvImport');
    Route::resource('peliculas', 'PeliculasController');

    // Boletos
    Route::delete('boletos/destroy', 'BoletosController@massDestroy')->name('boletos.massDestroy');
    Route::post('boletos/parse-csv-import', 'BoletosController@parseCsvImport')->name('boletos.parseCsvImport');
    Route::post('boletos/process-csv-import', 'BoletosController@processCsvImport')->name('boletos.processCsvImport');
    Route::resource('boletos', 'BoletosController');

    // Ctg Clientes
    Route::delete('ctg-clientes/destroy', 'CtgClienteController@massDestroy')->name('ctg-clientes.massDestroy');
    Route::post('ctg-clientes/media', 'CtgClienteController@storeMedia')->name('ctg-clientes.storeMedia');
    Route::post('ctg-clientes/ckmedia', 'CtgClienteController@storeCKEditorImages')->name('ctg-clientes.storeCKEditorImages');
    Route::post('ctg-clientes/parse-csv-import', 'CtgClienteController@parseCsvImport')->name('ctg-clientes.parseCsvImport');
    Route::post('ctg-clientes/process-csv-import', 'CtgClienteController@processCsvImport')->name('ctg-clientes.processCsvImport');
    Route::resource('ctg-clientes', 'CtgClienteController');

    // Clientecategoria
    Route::delete('clientecategoria/destroy', 'ClientecategoriaController@massDestroy')->name('clientecategoria.massDestroy');
    Route::post('clientecategoria/parse-csv-import', 'ClientecategoriaController@parseCsvImport')->name('clientecategoria.parseCsvImport');
    Route::post('clientecategoria/process-csv-import', 'ClientecategoriaController@processCsvImport')->name('clientecategoria.processCsvImport');
    Route::resource('clientecategoria', 'ClientecategoriaController');

    // Asientos
    Route::delete('asientos/destroy', 'AsientosController@massDestroy')->name('asientos.massDestroy');
    Route::post('asientos/parse-csv-import', 'AsientosController@parseCsvImport')->name('asientos.parseCsvImport');
    Route::post('asientos/process-csv-import', 'AsientosController@processCsvImport')->name('asientos.processCsvImport');
    Route::resource('asientos', 'AsientosController');

    // Salas
    Route::delete('salas/destroy', 'SalasController@massDestroy')->name('salas.massDestroy');
    Route::post('salas/parse-csv-import', 'SalasController@parseCsvImport')->name('salas.parseCsvImport');
    Route::post('salas/process-csv-import', 'SalasController@processCsvImport')->name('salas.processCsvImport');
    Route::resource('salas', 'SalasController');

    // Tickets
    Route::delete('tickets/destroy', 'TicketController@massDestroy')->name('tickets.massDestroy');
    Route::post('tickets/parse-csv-import', 'TicketController@parseCsvImport')->name('tickets.parseCsvImport');
    Route::post('tickets/process-csv-import', 'TicketController@processCsvImport')->name('tickets.processCsvImport');
    Route::resource('tickets', 'TicketController');

    // Teams
    Route::delete('teams/destroy', 'TeamController@massDestroy')->name('teams.massDestroy');
    Route::resource('teams', 'TeamController');

    Route::get('system-calendar', 'SystemCalendarController@index')->name('systemCalendar');
    Route::get('messenger', 'MessengerController@index')->name('messenger.index');
    Route::get('messenger/create', 'MessengerController@createTopic')->name('messenger.createTopic');
    Route::post('messenger', 'MessengerController@storeTopic')->name('messenger.storeTopic');
    Route::get('messenger/inbox', 'MessengerController@showInbox')->name('messenger.showInbox');
    Route::get('messenger/outbox', 'MessengerController@showOutbox')->name('messenger.showOutbox');
    Route::get('messenger/{topic}', 'MessengerController@showMessages')->name('messenger.showMessages');
    Route::delete('messenger/{topic}', 'MessengerController@destroyTopic')->name('messenger.destroyTopic');
    Route::post('messenger/{topic}/reply', 'MessengerController@replyToTopic')->name('messenger.reply');
    Route::get('messenger/{topic}/reply', 'MessengerController@showReply')->name('messenger.showReply');
});

LARAVEL/app/Boleto.php
<?php

namespace App;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Boleto extends Model
{
    use SoftDeletes;

    public $table = 'boletos';

    protected $dates = [
        'horario',
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    protected $fillable = [
        'precio',
        'horario',
        'id_boleto',
        'created_at',
        'updated_at',
        'deleted_at',
        'pelicula_id',
    ];

    public function idBoletoTickets()
    {
        return $this->hasMany(Ticket::class, 'id_boleto_id', 'id');

    }

    public function pelicula()
    {
        return $this->belongsTo(Pelicula::class, 'pelicula_id');

    }

    public function getHorarioAttribute($value)
    {
        return $value ? Carbon::createFromFormat('Y-m-d H:i:s', $value)->format(config('panel.date_format') . ' ' . config('panel.time_format')) : null;

    }

    public function setHorarioAttribute($value)
    {
        $this->attributes['horario'] = $value ? Carbon::createFromFormat(config('panel.date_format') . ' ' . config('panel.time_format'), $value)->format('Y-m-d H:i:s') : null;

    }
}

LARAVEL/app/Http/Controllers/Admin/BoletosController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Boleto;
use App\Http\Controllers\Controller;
use App\Http\Controllers\Traits\CsvImportTrait;
use App\Http\Requests\MassDestroyBoletoRequest;
use App\Http\Requests\StoreBoletoRequest;
use App\Http\Requests\UpdateBoletoRequest;
use App\Pelicula;
use Gate;
use Illuminate\Http\Request;
use Symfony\Component\HttpFoundation\Response;
use Yajra\DataTables\Facades\DataTables;

class BoletosController extends Controller
{
    use CsvImportTrait;

    public function index(Request $request)
    {
        abort_if(Gate::denies('boleto_access'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        if ($request->ajax()) {
            $query = Boleto::with(['pelicula'])->select(sprintf('%s.*', (new Boleto)->table));
            $table = Datatables::of($query);

            $table->addColumn('placeholder', '&nbsp;');
            $table->addColumn('actions', '&nbsp;');

            $table->editColumn('actions', function ($row) {
                $viewGate      = 'boleto_show';
                $editGate      = 'boleto_edit';
                $deleteGate    = 'boleto_delete';
                $crudRoutePart = 'boletos';

                return view('partials.datatablesActions', compact(
                    'viewGate',
                    'editGate',
                    'deleteGate',
                    'crudRoutePart',
                    'row'
                ));
            });

            $table->editColumn('id', function ($row) {
                return $row->id ? $row->id : "";
            });
            $table->editColumn('id_boleto', function ($row) {
                return $row->id_boleto ? $row->id_boleto : "";
            });
            $table->addColumn('pelicula_nombre', function ($row) {
                return $row->pelicula ? $row->pelicula->nombre : '';
            });

            $table->editColumn('precio', function ($row) {
                return $row->precio ? $row->precio : "";
            });

            $table->rawColumns(['actions', 'placeholder', 'pelicula']);

            return $table->make(true);
        }

        return view('admin.boletos.index');
    }

    public function create()
    {
        abort_if(Gate::denies('boleto_create'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $peliculas = Pelicula::all()->pluck('nombre', 'id')->prepend(trans('global.pleaseSelect'), '');

        return view('admin.boletos.create', compact('peliculas'));
    }

    public function store(StoreBoletoRequest $request)
    {
        $boleto = Boleto::create($request->all());

        return redirect()->route('admin.boletos.index');

    }

    public function edit(Boleto $boleto)
    {
        abort_if(Gate::denies('boleto_edit'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $peliculas = Pelicula::all()->pluck('nombre', 'id')->prepend(trans('global.pleaseSelect'), '');

        $boleto->load('pelicula');

        return view('admin.boletos.edit', compact('peliculas', 'boleto'));
    }

    public function update(UpdateBoletoRequest $request, Boleto $boleto)
    {
        $boleto->update($request->all());

        return redirect()->route('admin.boletos.index');

    }

    public function show(Boleto $boleto)
    {
        abort_if(Gate::denies('boleto_show'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $boleto->load('pelicula', 'idBoletoTickets');

        return view('admin.boletos.show', compact('boleto'));
    }

    public function destroy(Boleto $boleto)
    {
        abort_if(Gate::denies('boleto_delete'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $boleto->delete();

        return back();

    }

    public function massDestroy(MassDestroyBoletoRequest $request)
    {
        Boleto::whereIn('id', request('ids'))->delete();

        return response(null, Response::HTTP_NO_CONTENT);

    }

}

LARAVEL/resources/views/admin/boletos/relationships/idBoletoTickets.blade.php
<div class="content">
    @can('ticket_create')
        <div style="margin-bottom: 10px;" class="row">
            <div class="col-lg-12">
                <a class="btn btn-success" href="{{ route("admin.tickets.create") }}">
                    {{ trans('global.add') }} {{ trans('cruds.ticket.title_singular') }}
                </a>
            </div>
        </div>
    @endcan
    <div class="row">
        <div class="col-lg-12">

            <div class="panel panel-default">
                <div class="panel-heading">
                    {{ trans('cruds.ticket.title_singular') }} {{ trans('global.list') }}
                </div>
                <div class="panel-body">

                    <div class="table-responsive">
                        <table class=" table table-bordered table-striped table-hover datatable datatable-Ticket">
                            <thead>
                                <tr>
                                    <th width="10">

                                    </th>
                                    <th>
                                        {{ trans('cruds.ticket.fields.id') }}
                                    </th>
                                    <th>
                                        {{ trans('cruds.ticket.fields.id_ticket') }}
                                    </th>
                                    <th>
                                        {{ trans('cruds.ticket.fields.cliente') }}
                                    </th>
                                    <th>
                                        {{ trans('cruds.clientecategorium.fields.id_cat_user') }}
                                    </th>
                                    <th>
                                        {{ trans('cruds.ticket.fields.id_boleto') }}
                                    </th>
                                    <th>
                                        {{ trans('cruds.boleto.fields.precio') }}
                                    </th>
                                    <th>
                                        {{ trans('cruds.ticket.fields.asiento') }}
                                    </th>
                                    <th>
                                        &nbsp;
                                    </th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($tickets as $key => $ticket)
                                    <tr data-entry-id="{{ $ticket->id }}">
                                        <td>

                                        </td>
                                        <td>
                                            {{ $ticket->id ?? '' }}
                                        </td>
                                        <td>
                                            {{ $ticket->id_ticket ?? '' }}
                                        </td>
                                        <td>
                                            {{ $ticket->cliente->id_cat_user ?? '' }}
                                        </td>
                                        <td>
                                            {{ $ticket->cliente->id_cat_user ?? '' }}
                                        </td>
                                        <td>
                                            {{ $ticket->id_boleto->id_boleto ?? '' }}
                                        </td>
                                        <td>
                                            {{ $ticket->id_boleto->precio ?? '' }}
                                        </td>
                                        <td>
                                            {{ $ticket->asiento->id_asiento ?? '' }}
                                        </td>
                                        <td>
                                            @can('ticket_show')
                                                <a class="btn btn-xs btn-primary" href="{{ route('admin.tickets.show', $ticket->id) }}">
                                                    {{ trans('global.view') }}
                                                </a>
                                            @endcan

                                            @can('ticket_edit')
                                                <a class="btn btn-xs btn-info" href="{{ route('admin.tickets.edit', $ticket->id) }}">
                                                    {{ trans('global.edit') }}
                                                </a>
                                            @endcan

                                            @can('ticket_delete')
                                                <form action="{{ route('admin.tickets.destroy', $ticket->id) }}" method="POST" onsubmit="return confirm('{{ trans('global.areYouSure') }}');" style="display: inline-block;">
                                                    <input type="hidden" name="_method" value="DELETE">
                                                    <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                                    <input type="submit" class="btn btn-xs btn-danger" value="{{ trans('global.delete') }}">
                                                </form>
                                            @endcan

                                        </td>

                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>

                </div>
            </div>

        </div>
    </div>
</div>
@section('scripts')
@parent
<script>
    $(function () {
  let dtButtons = $.extend(true, [], $.fn.dataTable.defaults.buttons)
@can('ticket_delete')
  let deleteButtonTrans = '{{ trans('global.datatables.delete') }}'
  let deleteButton = {
    text: deleteButtonTrans,
    url: "{{ route('admin.tickets.massDestroy') }}",
    className: 'btn-danger',
    action: function (e, dt, node, config) {
      var ids = $.map(dt.rows({ selected: true }).nodes(), function (entry) {
          return $(entry).data('entry-id')
      });

      if (ids.length === 0) {
        alert('{{ trans('global.datatables.zero_selected') }}')

        return
      }

      if (confirm('{{ trans('global.areYouSure') }}')) {
        $.ajax({
          headers: {'x-csrf-token': _token},
          method: 'POST',
          url: config.url,
          data: { ids: ids, _method: 'DELETE' }})
          .done(function () { location.reload() })
      }
    }
  }
  dtButtons.push(deleteButton)
@endcan

  $.extend(true, $.fn.dataTable.defaults, {
    order: [[ 1, 'desc' ]],
    pageLength: 100,
  });
  $('.datatable-Ticket:not(.ajaxTable)').DataTable({ buttons: dtButtons })
    $('a[data-toggle="tab"]').on('shown.bs.tab', function(e){
        $($.fn.dataTable.tables(true)).DataTable()
            .columns.adjust();
    });
})

</script>
@endsection