LARAVEL/routes/web.php
<?php
Route::get('/welcome', function(){
    return view('welcome');
});
Route::get('/offline', function(){
    return view('modules/laravelpwa/offline');
});
Route::redirect('/', '/login');

Route::get('/home', function () {
    if (session('status')) {
        return redirect()->route('admin.home')->with('status', session('status'));
    }

    return redirect()->route('admin.home');
});

Auth::routes();
// Admin

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    // Permissions
    Route::delete('permissions/destroy', 'PermissionsController@massDestroy')->name('permissions.massDestroy');
    Route::resource('permissions', 'PermissionsController');

    // Roles
    Route::delete('roles/destroy', 'RolesController@massDestroy')->name('roles.massDestroy');
    Route::resource('roles', 'RolesController');

    // Users
    Route::delete('users/destroy', 'UsersController@massDestroy')->name('users.massDestroy');
    Route::post('users/parse-csv-import', 'UsersController@parseCsvImport')->name('users.parseCsvImport');
    Route::post('users/process-csv-import', 'UsersController@processCsvImport')->name('users.processCsvImport');
    Route::resource('users', 'UsersController');

    // Categoria
    Route::delete('categoria/destroy', 'CategoriaController@massDestroy')->name('categoria.massDestroy');
    Route::post('categoria/media', 'CategoriaController@storeMedia')->name('categoria.storeMedia');
    Route::post('categoria/ckmedia', 'CategoriaController@storeCKEditorImages')->name('categoria.storeCKEditorImages');
    Route::post('categoria/parse-csv-import', 'CategoriaController@parseCsvImport')->name('categoria.parseCsvImport');
    Route::post('categoria/process-csv-import', 'CategoriaController@processCsvImport')->name('categoria.processCsvImport');
    Route::resource('categoria', 'CategoriaController');

    // Clasificacions
    Route::delete('clasificacions/destroy', 'ClasificacionController@massDestroy')->name('clasificacions.massDestroy');
    Route::post('clasificacions/media', 'ClasificacionController@storeMedia')->name('clasificacions.storeMedia');
    Route::post('clasificacions/ckmedia', 'ClasificacionController@storeCKEditorImages')->name('clasificacions.storeCKEditorImages');
    Route::post('clasificacions/parse-csv-import', 'ClasificacionController@parseCsvImport')->name('clasificacions.parseCsvImport');
    Route::post('clasificacions/process-csv-import', 'ClasificacionController@processCsvImport')->name('clasificacions.processCsvImport');
    Route::resource('clasificacions', 'ClasificacionController');

    // Autors
    Route::delete('autors/destroy', 'AutorController@massDestroy')->name('autors.massDestroy');
    Route::post('autors/parse-csv-import', 'AutorController@parseCsvImport')->name('autors.parseCsvImport');
    Route::post('autors/process-csv-import', 'AutorController@processCsvImport')->name('autors.processCsvImport');
    Route::resource('autors', 'AutorController');

    // Peliculas
    Route::delete('peliculas/destroy', 'PeliculasController@massDestroy')->name('peliculas.massDestroy');
    Route::post('peliculas/parse-csv-import', 'PeliculasController@parseCsvImport')->name('peliculas.parseCsvImport');
    Route::post('peliculas/process-csv-import', 'PeliculasController@processCsvImport')->name('peliculas.processCsvImport');
    Route::resource('peliculas', 'PeliculasController');

    // Boletos
    Route::delete('boletos/destroy', 'BoletosController@massDestroy')->name('boletos.massDestroy');
    Route::post('boletos/parse-csv-import', 'BoletosController@parseCsvImport')->name('boletos.parseCsvImport');
    Route::post('boletos/process-csv-import', 'BoletosController@processCsvImport')->name('boletos.processCsvImport');
    Route::resource('boletos', 'BoletosController');

    // Ctg Clientes
    Route::delete('ctg-clientes/destroy', 'CtgClienteController@massDestroy')->name('ctg-clientes.massDestroy');
    Route::post('ctg-clientes/media', 'CtgClienteController@storeMedia')->name('ctg-clientes.storeMedia');
    Route::post('ctg-clientes/ckmedia', 'CtgClienteController@storeCKEditorImages')->name('ctg-clientes.storeCKEditorImages');
    Route::post('ctg-clientes/parse-csv-import', 'CtgClienteController@parseCsvImport')->name('ctg-clientes.parseCsvImport');
    Route::post('ctg-clientes/process-csv-import', 'CtgClienteController@processCsvImport')->name('ctg-clientes.processCsvImport');
    Route::resource('ctg-clientes', 'CtgClienteController');

    // Clientecategoria
    Route::delete('clientecategoria/destroy', 'ClientecategoriaController@massDestroy')->name('clientecategoria.massDestroy');
    Route::post('clientecategoria/parse-csv-import', 'ClientecategoriaController@parseCsvImport')->name('clientecategoria.parseCsvImport');
    Route::post('clientecategoria/process-csv-import', 'ClientecategoriaController@processCsvImport')->name('clientecategoria.processCsvImport');
    Route::resource('clientecategoria', 'ClientecategoriaController');

    // Asientos
    Route::delete('asientos/destroy', 'AsientosController@massDestroy')->name('asientos.massDestroy');
    Route::post('asientos/parse-csv-import', 'AsientosController@parseCsvImport')->name('asientos.parseCsvImport');
    Route::post('asientos/process-csv-import', 'AsientosController@processCsvImport')->name('asientos.processCsvImport');
    Route::resource('asientos', 'AsientosController');

    // Salas
    Route::delete('salas/destroy', 'SalasController@massDestroy')->name('salas.massDestroy');
    Route::post('salas/parse-csv-import', 'SalasController@parseCsvImport')->name('salas.parseCsvImport');
    Route::post('salas/process-csv-import', 'SalasController@processCsvImport')->name('salas.processCsvImport');
    Route::resource('salas', 'SalasController');

    // Tickets
    Route::delete('tickets/destroy', 'TicketController@massDestroy')->name('tickets.massDestroy');
    Route::post('tickets/parse-csv-import', 'TicketController@parseCsvImport')->name('tickets.parseCsvImport');
    Route::post('tickets/process-csv-import', 'TicketController@processCsvImport')->name('tickets.processCsvImport');
    Route::resource('tickets', 'TicketController');

    // Teams
    Route::delete('teams/destroy', 'TeamController@massDestroy')->name('teams.massDestroy');
    Route::resource('teams', 'TeamController');

    Route::get('system-calendar', 'SystemCalendarController@index')->name('systemCalendar');
    Route::get('messenger', 'MessengerController@index')->name('messenger.index');
    Route::get('messenger/create', 'MessengerController@createTopic')->name('messenger.createTopic');
    Route::post('messenger', 'MessengerController@storeTopic')->name('messenger.storeTopic');
    Route::get('messenger/inbox', 'MessengerController@showInbox')->name('messenger.showInbox');
    Route::get('messenger/outbox', 'MessengerController@showOutbox')->name('messenger.showOutbox');
    Route::get('messenger/{topic}', 'MessengerController@showMessages')->name('messenger.showMessages');
    Route::delete('messenger/{topic}', 'MessengerController@destroyTopic')->name('messenger.destroyTopic');
    Route::post('messenger/{topic}/reply', 'MessengerController@replyToTopic')->name('messenger.reply');
    Route::get('messenger/{topic}/reply', 'MessengerController@showReply')->name('messenger.showReply');
});

LARAVEL/resources/views/partials/datatablesActions.blade.php
@can($viewGate)
    <a class="btn btn-xs btn-primary" href="{{ route('admin.' . $crudRoutePart . '.show', $row->id) }}">
        {{ trans('global.view') }}
    </a>
@endcan
@can($editGate)
    <a class="btn btn-xs btn-info" href="{{ route('admin.' . $crudRoutePart . '.edit', $row->id) }}">
        {{ trans('global.edit') }}
    </a>
@endcan
@can($deleteGate)
    <form action="{{ route('admin.' . $crudRoutePart . '.destroy', $row->id) }}" method="POST" onsubmit="return confirm('{{ trans('global.areYouSure') }}');" style="display: inline-block;">
        <input type="hidden" name="_method" value="DELETE">
        <input type="hidden" name="_token" value="{{ csrf_token() }}">
        <input type="submit" class="btn btn-xs btn-danger" value="{{ trans('global.delete') }}">
    </form>
@endcan

LARAVEL/resources/views/partials/menu.blade.php
<aside class="main-sidebar">
    <section class="sidebar" style="height: auto;">
        <ul class="sidebar-menu tree" data-widget="tree">
            <li>
                <a href="{{ route("admin.home") }}">
                    <i class="fas fa-fw fa-tachometer-alt">

                    </i>
                    {{ trans('global.dashboard') }}
                </a>
            </li>
            @can('user_management_access')
                <li class="treeview">
                    <a href="#">
                        <i class="fa-fw fas fa-users">

                        </i>
                        <span>{{ trans('cruds.userManagement.title') }}</span>
                        <span class="pull-right-container"><i class="fa fa-fw fa-angle-left pull-right"></i></span>
                    </a>
                    <ul class="treeview-menu">
                        @can('permission_access')
                            <li class="{{ request()->is('admin/permissions') || request()->is('admin/permissions/*') ? 'active' : '' }}">
                                <a href="{{ route("admin.permissions.index") }}">
                                    <i class="fa-fw fas fa-unlock-alt">

                                    </i>
                                    <span>{{ trans('cruds.permission.title') }}</span>
                                </a>
                            </li>
                        @endcan
                        @can('role_access')
                            <li class="{{ request()->is('admin/roles') || request()->is('admin/roles/*') ? 'active' : '' }}">
                                <a href="{{ route("admin.roles.index") }}">
                                    <i class="fa-fw fas fa-briefcase">

                                    </i>
                                    <span>{{ trans('cruds.role.title') }}</span>
                                </a>
                            </li>
                        @endcan
                        @can('user_access')
                            <li class="{{ request()->is('admin/users') || request()->is('admin/users/*') ? 'active' : '' }}">
                                <a href="{{ route("admin.users.index") }}">
                                    <i class="fa-fw fas fa-user">

                                    </i>
                                    <span>{{ trans('cruds.user.title') }}</span>
                                </a>
                            </li>
                        @endcan
                        @can('team_access')
                            <li class="{{ request()->is('admin/teams') || request()->is('admin/teams/*') ? 'active' : '' }}">
                                <a href="{{ route("admin.teams.index") }}">
                                    <i class="fa-fw fas fa-users">

                                    </i>
                                    <span>{{ trans('cruds.team.title') }}</span>
                                </a>
                            </li>
                        @endcan
                    </ul>
                </li>
            @endcan
            @can('categorium_access')
                <li class="{{ request()->is('admin/categoria') || request()->is('admin/categoria/*') ? 'active' : '' }}">
                    <a href="{{ route("admin.categoria.index") }}">
                        <i class="fa-fw fas fa-bars">

                        </i>
                        <span>{{ trans('cruds.categorium.title') }}</span>
                    </a>
                </li>
            @endcan
            @can('clasificacion_access')
                <li class="{{ request()->is('admin/clasificacions') || request()->is('admin/clasificacions/*') ? 'active' : '' }}">
                    <a href="{{ route("admin.clasificacions.index") }}">
                        <i class="fa-fw far fa-clone">

                        </i>
                        <span>{{ trans('cruds.clasificacion.title') }}</span>
                    </a>
                </li>
            @endcan
            @can('autor_access')
                <li class="{{ request()->is('admin/autors') || request()->is('admin/autors/*') ? 'active' : '' }}">
                    <a href="{{ route("admin.autors.index") }}">
                        <i class="fa-fw fas fa-user-alt">

                        </i>
                        <span>{{ trans('cruds.autor.title') }}</span>
                    </a>
                </li>
            @endcan
            @can('pelicula_access')
                <li class="{{ request()->is('admin/peliculas') || request()->is('admin/peliculas/*') ? 'active' : '' }}">
                    <a href="{{ route("admin.peliculas.index") }}">
                        <i class="fa-fw fas fa-film">

                        </i>
                        <span>{{ trans('cruds.pelicula.title') }}</span>
                    </a>
                </li>
            @endcan
            @can('boleto_access')
                <li class="{{ request()->is('admin/boletos') || request()->is('admin/boletos/*') ? 'active' : '' }}">
                    <a href="{{ route("admin.boletos.index") }}">
                        <i class="fa-fw fas fa-ticket-alt">

                        </i>
                        <span>{{ trans('cruds.boleto.title') }}</span>
                    </a>
                </li>
            @endcan
            @can('ctg_cliente_access')
                <li class="{{ request()->is('admin/ctg-clientes') || request()->is('admin/ctg-clientes/*') ? 'active' : '' }}">
                    <a href="{{ route("admin.ctg-clientes.index") }}">
                        <i class="fa-fw fas fa-star">

                        </i>
                        <span>{{ trans('cruds.ctgCliente.title') }}</span>
                    </a>
                </li>
            @endcan
            @can('clientecategorium_access')
                <li class="{{ request()->is('admin/clientecategoria') || request()->is('admin/clientecategoria/*') ? 'active' : '' }}">
                    <a href="{{ route("admin.clientecategoria.index") }}">
                        <i class="fa-fw fas fa-diagnoses">

                        </i>
                        <span>{{ trans('cruds.clientecategorium.title') }}</span>
                    </a>
                </li>
            @endcan
            @can('asiento_access')
                <li class="{{ request()->is('admin/asientos') || request()->is('admin/asientos/*') ? 'active' : '' }}">
                    <a href="{{ route("admin.asientos.index") }}">
                        <i class="fa-fw fas fa-list-ol">

                        </i>
                        <span>{{ trans('cruds.asiento.title') }}</span>
                    </a>
                </li>
            @endcan
            @can('sala_access')
                <li class="{{ request()->is('admin/salas') || request()->is('admin/salas/*') ? 'active' : '' }}">
                    <a href="{{ route("admin.salas.index") }}">
                        <i class="fa-fw fas fa-store-alt">

                        </i>
                        <span>{{ trans('cruds.sala.title') }}</span>
                    </a>
                </li>
            @endcan
            @can('ticket_access')
                <li class="{{ request()->is('admin/tickets') || request()->is('admin/tickets/*') ? 'active' : '' }}">
                    <a href="{{ route("admin.tickets.index") }}">
                        <i class="fa-fw fas fa-shopping-cart">

                        </i>
                        <span>{{ trans('cruds.ticket.title') }}</span>
                    </a>
                </li>
            @endcan
            <li class="{{ request()->is('admin/system-calendar') || request()->is('admin/system-calendar/*') ? 'active' : '' }}">
                <a href="{{ route("admin.systemCalendar") }}">
                    <i class="fas fa-fw fa-calendar">

                    </i>
                    <span>{{ trans('global.systemCalendar') }}</span>
                </a>
            </li>
            @php($unread = \App\QaTopic::unreadCount())
                <li class="{{ request()->is('admin/messenger') || request()->is('admin/messenger/*') ? 'active' : '' }}">
                    <a href="{{ route("admin.messenger.index") }}">
                        <i class="fa-fw fa fa-envelope">

                        </i>
                        <span>{{ trans('global.messages') }}</span>
                        @if($unread > 0)
                            <strong>( {{ $unread }} )</strong>
                        @endif
                    </a>
                </li>
                <li>
                    <a href="#" onclick="event.preventDefault(); document.getElementById('logoutform').submit();">
                        <i class="fas fa-fw fa-sign-out-alt">

                        </i>
                        {{ trans('global.logout') }}
                    </a>
                </li>
        </ul>
    </section>
</aside>