LARAVEL/routes/web.php
<?php
Route::get('/welcome', function(){
    return view('welcome');
});
Route::get('/offline', function(){
    return view('modules/laravelpwa/offline');
});
Route::redirect('/', '/login');

Route::get('/home', function () {
    if (session('status')) {
        return redirect()->route('admin.home')->with('status', session('status'));
    }

    return redirect()->route('admin.home');
});

Auth::routes();
// Admin

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    // Permissions
    Route::delete('permissions/destroy', 'PermissionsController@massDestroy')->name('permissions.massDestroy');
    Route::resource('permissions', 'PermissionsController');

    // Roles
    Route::delete('roles/destroy', 'RolesController@massDestroy')->name('roles.massDestroy');
    Route::resource('roles', 'RolesController');

    // Users
    Route::delete('users/destroy', 'UsersController@massDestroy')->name('users.massDestroy');
    Route::post('users/parse-csv-import', 'UsersController@parseCsvImport')->name('users.parseCsvImport');
    Route::post('users/process-csv-import', 'UsersController@processCsvImport')->name('users.processCsvImport');
    Route::resource('users', 'UsersController');

    // Categoria
    Route::delete('categoria/destroy', 'CategoriaController@massDestroy')->name('categoria.massDestroy');
    Route::post('categoria/media', 'CategoriaController@storeMedia')->name('categoria.storeMedia');
    Route::post('categoria/ckmedia', 'CategoriaController@storeCKEditorImages')->name('categoria.storeCKEditorImages');
    Route::post('categoria/parse-csv-import', 'CategoriaController@parseCsvImport')->name('categoria.parseCsvImport');
    Route::post('categoria/process-csv-import', 'CategoriaController@processCsvImport')->name('categoria.processCsvImport');
    Route::resource('categoria', 'CategoriaController');

    // Clasificacions
    Route::delete('clasificacions/destroy', 'ClasificacionController@massDestroy')->name('clasificacions.massDestroy');
    Route::post('clasificacions/media', 'ClasificacionController@storeMedia')->name('clasificacions.storeMedia');
    Route::post('clasificacions/ckmedia', 'ClasificacionController@storeCKEditorImages')->name('clasificacions.storeCKEditorImages');
    Route::post('clasificacions/parse-csv-import', 'ClasificacionController@parseCsvImport')->name('clasificacions.parseCsvImport');
    Route::post('clasificacions/process-csv-import', 'ClasificacionController@processCsvImport')->name('clasificacions.processCsvImport');
    Route::resource('clasificacions', 'ClasificacionController');

    // Autors
    Route::delete('autors/destroy', 'AutorController@massDestroy')->name('autors.massDestroy');
    Route::post('autors/parse-csv-import', 'AutorController@parseCsvImport')->name('autors.parseCsvImport');
    Route::post('autors/process-csv-import', 'AutorController@processCsvImport')->name('autors.processCsvImport');
    Route::resource('autors', 'AutorController');

    // Peliculas
    Route::delete('peliculas/destroy', 'PeliculasController@massDestroy')->name('peliculas.massDestroy');
    Route::post('peliculas/parse-csv-import', 'PeliculasController@parseCsvImport')->name('peliculas.parseCsvImport');
    Route::post('peliculas/process-csv-import', 'PeliculasController@processCsvImport')->name('peliculas.processCsvImport');
    Route::resource('peliculas', 'PeliculasController');

    // Boletos
    Route::delete('boletos/destroy', 'BoletosController@massDestroy')->name('boletos.massDestroy');
    Route::post('boletos/parse-csv-import', 'BoletosController@parseCsvImport')->name('boletos.parseCsvImport');
    Route::post('boletos/process-csv-import', 'BoletosController@processCsvImport')->name('boletos.processCsvImport');
    Route::resource('boletos', 'BoletosController');

    // Ctg Clientes
    Route::delete('ctg-clientes/destroy', 'CtgClienteController@massDestroy')->name('ctg-clientes.massDestroy');
    Route::post('ctg-clientes/media', 'CtgClienteController@storeMedia')->name('ctg-clientes.storeMedia');
    Route::post('ctg-clientes/ckmedia', 'CtgClienteController@storeCKEditorImages')->name('ctg-clientes.storeCKEditorImages');
    Route::post('ctg-clientes/parse-csv-import', 'CtgClienteController@parseCsvImport')->name('ctg-clientes.parseCsvImport');
    Route::post('ctg-clientes/process-csv-import', 'CtgClienteController@processCsvImport')->name('ctg-clientes.processCsvImport');
    Route::resource('ctg-clientes', 'CtgClienteController');

    // Clientecategoria
    Route::delete('clientecategoria/destroy', 'ClientecategoriaController@massDestroy')->name('clientecategoria.massDestroy');
    Route::post('clientecategoria/parse-csv-import', 'ClientecategoriaController@parseCsvImport')->name('clientecategoria.parseCsvImport');
    Route::post('clientecategoria/process-csv-import', 'ClientecategoriaController@processCsvImport')->name('clientecategoria.processCsvImport');
    Route::resource('clientecategoria', 'ClientecategoriaController');

    // Asientos
    Route::delete('asientos/destroy', 'AsientosController@massDestroy')->name('asientos.massDestroy');
    Route::post('asientos/parse-csv-import', 'AsientosController@parseCsvImport')->name('asientos.parseCsvImport');
    Route::post('asientos/process-csv-import', 'AsientosController@processCsvImport')->name('asientos.processCsvImport');
    Route::resource('asientos', 'AsientosController');

    // Salas
    Route::delete('salas/destroy', 'SalasController@massDestroy')->name('salas.massDestroy');
    Route::post('salas/parse-csv-import', 'SalasController@parseCsvImport')->name('salas.parseCsvImport');
    Route::post('salas/process-csv-import', 'SalasController@processCsvImport')->name('salas.processCsvImport');
    Route::resource('salas', 'SalasController');

    // Tickets
    Route::delete('tickets/destroy', 'TicketController@massDestroy')->name('tickets.massDestroy');
    Route::post('tickets/parse-csv-import', 'TicketController@parseCsvImport')->name('tickets.parseCsvImport');
    Route::post('tickets/process-csv-import', 'TicketController@processCsvImport')->name('tickets.processCsvImport');
    Route::resource('tickets', 'TicketController');

    // Teams
    Route::delete('teams/destroy', 'TeamController@massDestroy')->name('teams.massDestroy');
    Route::resource('teams', 'TeamController');

    Route::get('system-calendar', 'SystemCalendarController@index')->name('systemCalendar');
    Route::get('messenger', 'MessengerController@index')->name('messenger.index');
    Route::get('messenger/create', 'MessengerController@createTopic')->name('messenger.createTopic');
    Route::post('messenger', 'MessengerController@storeTopic')->name('messenger.storeTopic');
    Route::get('messenger/inbox', 'MessengerController@showInbox')->name('messenger.showInbox');
    Route::get('messenger/outbox', 'MessengerController@showOutbox')->name('messenger.showOutbox');
    Route::get('messenger/{topic}', 'MessengerController@showMessages')->name('messenger.showMessages');
    Route::delete('messenger/{topic}', 'MessengerController@destroyTopic')->name('messenger.destroyTopic');
    Route::post('messenger/{topic}/reply', 'MessengerController@replyToTopic')->name('messenger.reply');
    Route::get('messenger/{topic}/reply', 'MessengerController@showReply')->name('messenger.showReply');
});

LARAVEL/app/CtgCliente.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Spatie\MediaLibrary\HasMedia\HasMedia;
use Spatie\MediaLibrary\HasMedia\HasMediaTrait;
use Spatie\MediaLibrary\Models\Media;

class CtgCliente extends Model implements HasMedia
{
    use SoftDeletes, HasMediaTrait;

    public $table = 'ctg_clientes';

    protected $dates = [
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    protected $fillable = [
        'created_at',
        'updated_at',
        'deleted_at',
        'descripcion',
        'id_categoria',
    ];

    public function registerMediaConversions(Media $media = null)
    {
        $this->addMediaConversion('thumb')->width(50)->height(50);

    }

    public function categoriaClientecategoria()
    {
        return $this->hasMany(Clientecategorium::class, 'categoria_id', 'id');

    }
}

LARAVEL/app/Http/Controllers/Admin/CtgClienteController.php
<?php

namespace App\Http\Controllers\Admin;

use App\CtgCliente;
use App\Http\Controllers\Controller;
use App\Http\Controllers\Traits\CsvImportTrait;
use App\Http\Controllers\Traits\MediaUploadingTrait;
use App\Http\Requests\MassDestroyCtgClienteRequest;
use App\Http\Requests\StoreCtgClienteRequest;
use App\Http\Requests\UpdateCtgClienteRequest;
use Gate;
use Illuminate\Http\Request;
use Spatie\MediaLibrary\Models\Media;
use Symfony\Component\HttpFoundation\Response;
use Yajra\DataTables\Facades\DataTables;

class CtgClienteController extends Controller
{
    use MediaUploadingTrait, CsvImportTrait;

    public function index(Request $request)
    {
        abort_if(Gate::denies('ctg_cliente_access'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        if ($request->ajax()) {
            $query = CtgCliente::query()->select(sprintf('%s.*', (new CtgCliente)->table));
            $table = Datatables::of($query);

            $table->addColumn('placeholder', '&nbsp;');
            $table->addColumn('actions', '&nbsp;');

            $table->editColumn('actions', function ($row) {
                $viewGate      = 'ctg_cliente_show';
                $editGate      = 'ctg_cliente_edit';
                $deleteGate    = 'ctg_cliente_delete';
                $crudRoutePart = 'ctg-clientes';

                return view('partials.datatablesActions', compact(
                    'viewGate',
                    'editGate',
                    'deleteGate',
                    'crudRoutePart',
                    'row'
                ));
            });

            $table->editColumn('id', function ($row) {
                return $row->id ? $row->id : "";
            });
            $table->editColumn('id_categoria', function ($row) {
                return $row->id_categoria ? $row->id_categoria : "";
            });

            $table->rawColumns(['actions', 'placeholder']);

            return $table->make(true);
        }

        return view('admin.ctgClientes.index');
    }

    public function create()
    {
        abort_if(Gate::denies('ctg_cliente_create'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        return view('admin.ctgClientes.create');
    }

    public function store(StoreCtgClienteRequest $request)
    {
        $ctgCliente = CtgCliente::create($request->all());

        if ($media = $request->input('ck-media', false)) {
            Media::whereIn('id', $media)->update(['model_id' => $ctgCliente->id]);
        }

        return redirect()->route('admin.ctg-clientes.index');

    }

    public function edit(CtgCliente $ctgCliente)
    {
        abort_if(Gate::denies('ctg_cliente_edit'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        return view('admin.ctgClientes.edit', compact('ctgCliente'));
    }

    public function update(UpdateCtgClienteRequest $request, CtgCliente $ctgCliente)
    {
        $ctgCliente->update($request->all());

        return redirect()->route('admin.ctg-clientes.index');

    }

    public function show(CtgCliente $ctgCliente)
    {
        abort_if(Gate::denies('ctg_cliente_show'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $ctgCliente->load('categoriaClientecategoria');

        return view('admin.ctgClientes.show', compact('ctgCliente'));
    }

    public function destroy(CtgCliente $ctgCliente)
    {
        abort_if(Gate::denies('ctg_cliente_delete'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $ctgCliente->delete();

        return back();

    }

    public function massDestroy(MassDestroyCtgClienteRequest $request)
    {
        CtgCliente::whereIn('id', request('ids'))->delete();

        return response(null, Response::HTTP_NO_CONTENT);

    }

    public function storeCKEditorImages(Request $request)
    {
        abort_if(Gate::denies('ctg_cliente_create') && Gate::denies('ctg_cliente_edit'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $model         = new CtgCliente();
        $model->id     = $request->input('crud_id', 0);
        $model->exists = true;
        $media         = $model->addMediaFromRequest('upload')->toMediaCollection('ck-media', 'public');

        return response()->json(['id' => $media->id, 'url' => $media->getUrl()], Response::HTTP_CREATED);

    }

}

LARAVEL/resources/views/admin/ctgClientes/relationships/categoriaClientecategoria.blade.php
<div class="content">
    @can('clientecategorium_create')
        <div style="margin-bottom: 10px;" class="row">
            <div class="col-lg-12">
                <a class="btn btn-success" href="{{ route("admin.clientecategoria.create") }}">
                    {{ trans('global.add') }} {{ trans('cruds.clientecategorium.title_singular') }}
                </a>
            </div>
        </div>
    @endcan
    <div class="row">
        <div class="col-lg-12">

            <div class="panel panel-default">
                <div class="panel-heading">
                    {{ trans('cruds.clientecategorium.title_singular') }} {{ trans('global.list') }}
                </div>
                <div class="panel-body">

                    <div class="table-responsive">
                        <table class=" table table-bordered table-striped table-hover datatable datatable-Clientecategorium">
                            <thead>
                                <tr>
                                    <th width="10">

                                    </th>
                                    <th>
                                        {{ trans('cruds.clientecategorium.fields.id') }}
                                    </th>
                                    <th>
                                        {{ trans('cruds.clientecategorium.fields.id_cat_user') }}
                                    </th>
                                    <th>
                                        {{ trans('cruds.clientecategorium.fields.cliente') }}
                                    </th>
                                    <th>
                                        {{ trans('cruds.user.fields.email') }}
                                    </th>
                                    <th>
                                        {{ trans('cruds.clientecategorium.fields.categoria') }}
                                    </th>
                                    <th>
                                        {{ trans('cruds.ctgCliente.fields.id_categoria') }}
                                    </th>
                                    <th>
                                        &nbsp;
                                    </th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($clientecategoria as $key => $clientecategorium)
                                    <tr data-entry-id="{{ $clientecategorium->id }}">
                                        <td>

                                        </td>
                                        <td>
                                            {{ $clientecategorium->id ?? '' }}
                                        </td>
                                        <td>
                                            {{ $clientecategorium->id_cat_user ?? '' }}
                                        </td>
                                        <td>
                                            {{ $clientecategorium->cliente->name ?? '' }}
                                        </td>
                                        <td>
                                            {{ $clientecategorium->cliente->email ?? '' }}
                                        </td>
                                        <td>
                                            {{ $clientecategorium->categoria->id_categoria ?? '' }}
                                        </td>
                                        <td>
                                            {{ $clientecategorium->categoria->id_categoria ?? '' }}
                                        </td>
                                        <td>
                                            @can('clientecategorium_show')
                                                <a class="btn btn-xs btn-primary" href="{{ route('admin.clientecategoria.show', $clientecategorium->id) }}">
                                                    {{ trans('global.view') }}
                                                </a>
                                            @endcan

                                            @can('clientecategorium_edit')
                                                <a class="btn btn-xs btn-info" href="{{ route('admin.clientecategoria.edit', $clientecategorium->id) }}">
                                                    {{ trans('global.edit') }}
                                                </a>
                                            @endcan

                                            @can('clientecategorium_delete')
                                                <form action="{{ route('admin.clientecategoria.destroy', $clientecategorium->id) }}" method="POST" onsubmit="return confirm('{{ trans('global.areYouSure') }}');" style="display: inline-block;">
                                                    <input type="hidden" name="_method" value="DELETE">
                                                    <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                                    <input type="submit" class="btn btn-xs btn-danger" value="{{ trans('global.delete') }}">
                                                </form>
                                            @endcan

                                        </td>

                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>

                </div>
            </div>

        </div>
    </div>
</div>
@section('scripts')
@parent
<script>
    $(function () {
  let dtButtons = $.extend(true, [], $.fn.dataTable.defaults.buttons)
@can('clientecategorium_delete')
  let deleteButtonTrans = '{{ trans('global.datatables.delete') }}'
  let deleteButton = {
    text: deleteButtonTrans,
    url: "{{ route('admin.clientecategoria.massDestroy') }}",
    className: 'btn-danger',
    action: function (e, dt, node, config) {
      var ids = $.map(dt.rows({ selected: true }).nodes(), function (entry) {
          return $(entry).data('entry-id')
      });

      if (ids.length === 0) {
        alert('{{ trans('global.datatables.zero_selected') }}')

        return
      }

      if (confirm('{{ trans('global.areYouSure') }}')) {
        $.ajax({
          headers: {'x-csrf-token': _token},
          method: 'POST',
          url: config.url,
          data: { ids: ids, _method: 'DELETE' }})
          .done(function () { location.reload() })
      }
    }
  }
  dtButtons.push(deleteButton)
@endcan

  $.extend(true, $.fn.dataTable.defaults, {
    order: [[ 1, 'desc' ]],
    pageLength: 100,
  });
  $('.datatable-Clientecategorium:not(.ajaxTable)').DataTable({ buttons: dtButtons })
    $('a[data-toggle="tab"]').on('shown.bs.tab', function(e){
        $($.fn.dataTable.tables(true)).DataTable()
            .columns.adjust();
    });
})

</script>
@endsection